version: '3'
services:
  backend:
    build: .
    ports:
      - "50051:50051"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./src:/app/src
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    command: npm start

  envoy:
    image: envoyproxy/envoy:v1.28.0
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]